### PR TITLE
fix(examples-tutorial-basis): unbreak wasm-test by forwarding client-router and replacing success_url

### LINKED ISSUE #4599: Bug: examples-tutorial-basis fails — page!/watch! syntax error, missing resolve_client_url, superuser test panic
## Describe the bug

\`examples-tutorial-basis\` produces three failures during CI build + tests:

### 1. Compile syntax error in \`page!\` / \`watch!\` macro emission

\`\`\`
error: expected \`:\`
  --> ... line 24,  state: { loading, error },
  --> ... line 120, state: { loading, error },
  --> ... line 184, state: { loading, error },
\`\`\`

Three call sites in the tutorial code generate emissions ending with \`state: { loading, error },\` that fail Rust parsing. Likely the \`page!\` or \`watch!\` macro contract has changed and the tutorial's hand-written usage is out of date.

### 2. \`ResolvedUrls::resolve_client_url\` not found

\`\`\`
error[E0599]: no method named \`resolve_client_url\` found for struct \`ResolvedUrls\` in the current scope
\`\`\`

\`ResolvedUrls\` no longer exposes \`resolve_client_url\` as an inherent method. The tutorial references the old API directly. The new API likely requires bringing \`ClientUrlResolver\` into scope or using the typed accessor introduced in PR #4518 \`fix(macros): typed ResolvedUrls accessors for ViewSet and #[action]\` and PR #4580 \`docs(examples): migrate examples-tutorial-rest to typed ResolvedUrls accessor\` (which migrated \`examples-tutorial-rest\` — the equivalent migration was missed for \`examples-tutorial-basis\`).

### 3. Superuser inventory test panic

\`\`\`
FAIL [   0.013s] (11/28) examples-tutorial-basis::createsuperuser tutorial_user_is_registered_in_superuser_creator_inventory
thread 'tutorial_user_is_registered_in_superuser_creator_inventory' panicked at examples-tutorial-basis/tests/createsuperuser.rs:106:5
\`\`\`

The tutorial \`User\` type is not appearing in the \`SuperuserCreator\` inventory expected by the test. This likely interacts with the framework changes from PR #4545 \`feat(core): auto-register SuperuserCreator for any #[user] + #[model] type\` and PR #4544 \`fix(examples-tutorial-basis): wire createsuperuser for minimal user model\`.

## Reproduction

\`\`\`
cd examples/examples-tutorial-basis
cargo build --all-features
cargo nextest run --all-features
\`\`\`

Observed CI failure on PR #4595 \`chore: release\`: <https://github.com/kent8192/reinhardt-web/actions/runs/26040399559/job/76619077831>

## Expected behavior

\`examples-tutorial-basis\` compiles and all tests pass under the current framework version.

## Suggested fix

Three sub-fixes within the same examples crate (single PR per WU-2):

1. Migrate \`page!\` / \`watch!\` call sites (lines around 24, 120, 184) to the current macro contract — likely change \`state: { loading, error }\` to the new syntax.
2. Replace \`resolved_urls.resolve_client_url(...)\` calls with the typed accessor pattern from PR #4518 / #4580 (e.g., \`use reinhardt::ClientUrlResolver;\` then call via trait, or use \`urls.client().<app>().<route>(...)\`).
3. Diagnose why the tutorial \`User\` is not auto-registered in \`SuperuserCreator\` inventory after PR #4545 — verify \`#[user] + #[model]\` placement, feature flags, and the test's expectation against the new inventory contract.

## Environment

- Crate: \`examples-tutorial-basis\`
- Related: PR #4518, #4544, #4545, #4580

### PR DESCRIPTION
**Pull request by kent8192**
## Summary

Unblocks the `examples-tutorial-basis` CI test job (`Examples Tests (Standalone)`), which has been failing on every Release PR with two compile errors during the WASM test build:

```
error: expected `:`
  --> .../polls.rs:184:16     // success_url: |_form, _value| links::poll_results(qid),
error[E0599]: no method named `resolve_client_url` found for struct `ResolvedUrls`
  --> .../links.rs:23:9
```

Two narrowly-scoped commits, both confined to `examples/examples-tutorial-basis`:

1. **`Makefile.toml` — forward `--features client-router` to `wasm-pack test`.** `cargo make wasm-test` already passes `--no-default-features` so the `with-reinhardt`-gated `manage` bin gets skipped, but that also disables the example's default `client-router` feature flag — which is exactly what the `#[routes]` macro's `impl ClientUrlResolver for ResolvedUrls` block gates on at expansion time in the consumer crate (see `crates/reinhardt-core/macros/src/routes_registration.rs` around the `ResolvedUrls` definition). Without the impl in scope, `src/client/links.rs::resolve(...)` cannot call `resolve_client_url(name, params)`.
2. **`polls.rs` — replace broken `success_url:` closure with a `state: { ..., success }` + sibling `use_effect`.** Two upstream defects make `success_url: |_form, _value| <expr>` unusable today: (a) the `reinhardt-manouche` form parser arm for `success_url` consumes a redundant `:` (`crates/reinhardt-manouche/src/parser/form.rs:117-121`), and (b) the `on_success` codegen embeds the user closure inside the generated form struct's `submit()` method, which is a `fn` item that cannot capture enclosing-scope locals like `qid`. The replacement reads `voting_form.success().get()` from `use_effect`, which IS bound in the outer scope where `qid` lives, and the `if did_succeed` guard preserves PR #4519's one-shot semantics (no redirect on mount).

The reported "Failure 3" (`tutorial_user_is_registered_in_superuser_creator_inventory` panic) is **not actually reproducible**: in CI run [26040399559](https://github.com/kent8192/reinhardt-web/actions/runs/26040399559) the `Test` step never got past the two compile errors above, so the test binary was never linked or executed. The most recent successful `Examples Tests (Standalone)` runs on branches that don't carry the `success_url` regression all show this test passing (see e.g. run [26075253066](https://github.com/kent8192/reinhardt-web/actions/runs/26075253066)). The macro auto-registration introduced by #4545 / verified by #4563 continues to work.

Fixes #4599

## Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature
- [ ] Breaking change
- [x] Documentation update (inline workaround comments per `instructions/ANTI_PATTERNS.md` workaround template)
- [ ] Code refactoring
- [ ] Performance improvement
- [ ] Test addition or update
- [ ] CI/CD update

## Motivation and Context

`examples-tutorial-basis` is the canonical onboarding example for the Pages stack — it must build cleanly on both native and `wasm32-unknown-unknown` against the current framework. PR #4519 / commit 25695a56cf introduced `success_url:` to fix a redirect-on-mount bug from PR #4517, but neither the `reinhardt-manouche` parser nor the `reinhardt-pages` codegen actually support that property end-to-end. Combined with the `--no-default-features` test build dropping the `client-router` impl in the macro emission, the example crate has been red on every Release PR since.

This commit fixes the example without depending on any framework crate landing first; the two underlying framework defects need their own PRs.

## Framework Bugs Discovered (for separate follow-up PRs)

Per the instruction in #4599 ("If during investigation any single sub-failure turns out to be a framework bug, STOP and report"), the following are NOT addressed here:

- **`reinhardt-manouche` parser bug — `success_url:` arm consumes a redundant colon.** `crates/reinhardt-manouche/src/parser/form.rs:117-121` does `let _colon: Token![:] = input.parse()?;` *after* the outer loop at line 38 already consumed the `:` between the key and the value. Every other arm in the same loop (`name`, `action`, `server_fn`, `state`, `on_submit`, `on_success`, …) skips the redundant parse. The 1-line fix is to remove that `let _colon` line. No test exercises this arm today — the property is never functional. Will file a dedicated framework issue + PR.

- **`reinhardt-pages` `on_success`/`success_url` codegen cannot capture enclosing locals.** `generate_on_success_callback` in `crates/reinhardt-pages/macros/src/form/codegen.rs` places the user closure inside the struct's `submit()` method body. `watch:` and `initial:` work around this by binding the user closure / expression in the outer `let mut __reinhardt_form = #struct_name::new(); ... #initial_outer_setup; #watch_outer_setup;` block where the form is constructed (issues #4414 / #4420). `on_success:` / `success_url:` need the same treatment.

## How Was This Tested

- [x] `cargo check --all-features` in `examples/examples-tutorial-basis` (native) — clean, 14m 31s on first cold build, 0 warnings, 0 errors
- [x] `cargo check --target wasm32-unknown-unknown --no-default-features --features client-router` in `examples/examples-tutorial-basis` — clean, only the 3 pre-existing `__FORM_CSRF_AUTO_INJECT_DEPRECATED` warnings (tracked in #3971, not in scope)
- [ ] Full `cargo nextest run --all-features --no-fail-fast` — relying on CI; locally `cargo nextest run --all-features --no-fail-fast --test createsuperuser` was attempted but is gated by the same fix, so it now compiles for the first time. CI's `Test` step (which runs the full nextest suite) will validate the `tutorial_user_is_registered_in_superuser_creator_inventory` test that #4599 hypothesised would fail — based on the most recent green runs on adjacent branches, it is expected to pass.
- [ ] `cargo make fmt-check` — pre-existing rustfmt diffs at `polls.rs:95`, `:444`, `:596` exist on `main` independently of this PR (verified by `git stash`). The CI `Check Format` step uses the project-local `cargo make fmt-check` (`reinhardt-admin-cli fmt-all --check`) which passed on the cited failing run, so these are formatter artefacts of the `page!` macro, not real fmt issues.

## Checklist

- [x] My code follows the project's style guidelines
- [x] PR title follows Conventional Commits format
- [x] All comments are in English
- [x] Workaround comments include the ideal implementation per the `instructions/ANTI_PATTERNS.md` template
- [x] No new `todo!()` / `// TODO:` introduced
- [x] Linked Issue (Fixes #4599)
- [ ] Tests added/updated where applicable (existing test coverage in `tests/createsuperuser.rs` is now reachable for the first time since #4519 landed)

## Labels to Apply

- bug
- examples
- documentation

🤖 Generated with [Claude Code](https://claude.com/claude-code)

## Summary by CodeRabbit

* **Bug Fixes**
  * Improved voting form success handling to perform a reliable client-side redirect to poll results after a successful vote.

* **Chores**
  * Updated WASM test task configuration to forward an additional feature flag so tests build and run with required routing support.

[Review Change Stack](https://app.coderabbit.ai/change-stack/kent8192/reinhardt-web/pull/4603?utm_source=github_walkthrough&utm_medium=github&utm_campaign=change_stack)

### CODE REVIEW

File: examples/examples-tutorial-basis/src/client/components/polls.rs [hunk 1]
```diff
@@ -237,6 +249,33 @@ pub fn polls_detail(question_id: i64) -> Page {
...
+			if did_succeed {
+				#[cfg(all(target_family = "wasm", target_os = "unknown"))]
+				{
+					if let Some(window) = web_sys::window() {
+						let _ = window.location().set_href(&dest);
+					}
+				}
+			}
+		});
+	}
```
[the remark this answers is not in the document]
Comment (kent8192) [reply examples/examples-tutorial-basis/src/client/components/polls.rs:280]: Addressed in 1581334. Moved the `#[cfg(all(target_family = "wasm", target_os = "unknown"))]` guard from inside the closure body up to the entire scope so the `voting_form` clone, `dest` allocation, and `use_effect` registration are all elided on native/SSR builds.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

File: examples/examples-tutorial-basis/src/client/components/polls.rs [hunk 2]
```diff
@@ -237,6 +249,33 @@ pub fn polls_detail(question_id: i64) -> Page {
...
+	{
+		let voting_form_for_redirect = voting_form.clone();
+		let dest = links::poll_results(qid);
+		use_effect(move || {
+			let did_succeed = voting_form_for_redirect.success().get();
+			if did_succeed {
+				#[cfg(all(target_family = "wasm", target_os = "unknown"))]
+				{
+					if let Some(window) = web_sys::window() {
+						let _ = window.location().set_href(&dest);
```
[the remark this answers is not in the document]
Comment (kent8192) [reply examples/examples-tutorial-basis/src/client/components/polls.rs]: Not addressed in this PR; tracking in #4610. Rationale: no public imperative SPA navigation API exists today (`reinhardt-pages` re-exports `push_state`/`replace_state` as `pub(super)`, and the `Router` instance is not accessible from `use_effect` scope), so this example mirrors the framework's own form-macro success_url codegen (`crates/reinhardt-pages/macros/src/form/codegen.rs:1003,2101,2111,2159`) which also uses `window.location().set_href(...)`. Switching to router-based navigation requires the new public API proposed in #4610.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

File: examples/examples-tutorial-basis/src/client/components/polls.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (kent8192) [reply examples/examples-tutorial-basis/src/client/components/polls.rs:280]: Not addressed here; tracking the underlying framework defects in #4611 (`reinhardt-manouche` parser arm consumes redundant `:`) and #4612 (`reinhardt-pages` `on_success`/`success_url` codegen cannot capture enclosing-scope locals). Rationale: this example explicitly enables `client-router` and is exercised via `wasm-pack test`; a server-side (no-JS) success redirect requires a working `success_url:` end-to-end, which depends on both fixes landing — restoring that path here today would require duplicating the framework defects.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
