### ISSUE TITLE
test(db): add CockroachDB regression case to test_alter_column_type_rollback

### ISSUE THREAD

**Issue by kent8192** [kent8192/reinhardt-web#4639]
## Prerequisites

- [x] I have searched existing issues to verify this feature hasn't been requested

## Summary

Add a CockroachDB regression case to `tests/integration/tests/migrations/migration_rollback_integration.rs::test_alter_column_type_rollback` so that the CockroachDB-specific stop-gap behavior introduced in #4633 (column-type reversion only, no NOT NULL fidelity) cannot silently regress in CI.

This is the **main-targeting, non-breaking** half of #4634. The full `Vec<String>` API refactor that restores NOT NULL fidelity is tracked separately and targets `develop/0.2.0`.

## Motivation / Problem

PR #4633 (merged as `556e4605e7`) split the `Operation::AlterColumn` reverse-SQL path so that:

- **PostgreSQL** emits a single comma-separated `ALTER TABLE ... ALTER COLUMN c TYPE T, ALTER COLUMN c {SET|DROP} NOT NULL;` (full fidelity).
- **CockroachDB** emits only `ALTER TABLE ... ALTER COLUMN c TYPE T;` (NOT NULL fidelity intentionally dropped because CockroachDB rejects the comma-combined form and the current `to_reverse_sql` API returns a single `String`).

Today, the parametrized `test_alter_column_type_rollback` only runs against Postgres / MySQL / SQLite. The CockroachDB branch is therefore exercised by **zero automated tests**: any future regression that breaks even the type-reversion-only path will pass CI silently and only surface in downstream CockroachDB deployments.

Adding a CockroachDB regression case closes this CI gap.

## Proposed Solution

Add a standalone test function `test_alter_column_type_rollback_cockroachdb` in `tests/integration/tests/migrations/migration_rollback_integration.rs`, modeled on `tests/integration/tests/migrations/db_specific_optimizations.rs::test_cockroachdb_interleave_table` and `tests/integration/tests/dcl/cockroachdb_tests.rs`. The test:

- Uses the existing `cockroachdb_container()` fixture from `reinhardt_test::fixtures::testcontainers`.
- Connects via `DatabaseConnection::connect_postgres(&url)` (CockroachDB speaks the Postgres wire protocol).
- Uses `#[serial(alter_column_rollback_cockroach)]` to serialize container access.
- Mirrors the parametrized test's flow: create a `products` table with `name VARCHAR(50)`, alter to `TEXT`, rollback, then assert that the column still exists and the type reverts to `VARCHAR`.
- **Does NOT** assert NOT NULL fidelity — that assertion is deferred to the `develop/0.2.0` Issue.

Why not extend the parametrized matrix instead? `DatabaseType` (used by `setup_backend`) has only three variants (`Postgres / Sqlite / Mysql`) and is **not** `#[non_exhaustive]`. Adding a `Cockroachdb` variant is a SemVer-breaking change to a public enum and is therefore out of scope for a `main`-targeting PR during the 0.1.0-rc series (per Stability Policy DB-2).

## Alternatives Considered

- **Adding `DatabaseType::Cockroachdb` and extending `#[case::cockroach(...)]`.** Rejected: SemVer-breaking on a non-`non_exhaustive` public enum. Belongs on `develop/0.2.0`.
- **Adding `#[non_exhaustive]` to `DatabaseType` first.** Rejected: adding `#[non_exhaustive]` is itself a breaking change for downstream exhaustive matches.

## Additional Context

- Split-out of #4634 (per maintainer scoping decision: main = non-breaking regression coverage, develop/0.2.0 = breaking API refactor).
- Companion Issue for the API refactor on `develop/0.2.0` will be filed alongside this one.
- Refs #4633, #4634.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by kent8192** [comment]
Companion Issue created: #4640 (develop/0.2.0-targeting `Vec<String>` API refactor — restores NOT NULL fidelity on CockroachDB once the API change lands).

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by kent8192** [comment]
**Implementation pivot: integration test → unit test (scope unchanged).**

While implementing the originally proposed `test_alter_column_type_rollback_cockroachdb` integration test, I discovered that `DatabaseMigrationExecutor::apply_migrations` calls `pg_advisory_lock()` — a PostgreSQL function CockroachDB does not implement. The first migration in the test never even gets to `Operation::AlterColumn` because lock acquisition aborts with:

```
DatabaseError(QueryError("unknown function: pg_advisory_lock(): function undefined"))
```

This is an independent executor-layer bug, now tracked as #4642 (`agent-suspect` until independently verified). Until that lands, no migration can run against CockroachDB through the standard executor path, so an integration test cannot provide regression coverage today.

**Pivoted approach (same regression-coverage intent, different layer):** add `test_to_reverse_sql_alter_column_cockroachdb` as a unit test alongside the existing `test_to_reverse_sql_alter_column_postgres / _mysql / _sqlite` cases in `crates/reinhardt-db/src/migrations/operations.rs`. The test asserts that:

1. CockroachDB `AlterColumn` reverse SQL emits exactly one statement (catches any regression toward the Postgres comma-combined form CockroachDB rejects).
2. The statement uses `ALTER COLUMN ... TYPE` syntax with the original type restored.
3. The statement does **not** contain `SET NOT NULL` / `DROP NOT NULL` — that's the stop-gap fidelity gap that #4640 will close.

This directly guards the stop-gap output shape introduced by #4633, runs in <1ms with no container infrastructure, and would have caught the documented regression class without needing the executor to work end-to-end. The end-to-end CockroachDB integration coverage moves naturally to #4640 once both the `Vec<String>` API and #4642's executor fix are in place.

Updated dependency chain:

- **This Issue (#4639)** → unit-test stop-gap regression coverage on `main` (this comment + branch `test/issue-4639-cockroachdb-alter-column-rollback-coverage`).
- **#4642** → `pg_advisory_lock` executor incompatibility, unblocks end-to-end CockroachDB tests.
- **#4640** → `Vec<String>` API refactor on `develop/0.2.0`, restores NOT NULL fidelity, and (depending on #4642 status) adds the integration test.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
