### ISSUE TITLE
Bug: examples-tutorial-basis fails — page!/watch! syntax error, missing resolve_client_url, superuser test panic

### ISSUE THREAD

**Issue by kent8192** [kent8192/reinhardt-web#4599]
## Describe the bug

\`examples-tutorial-basis\` produces three failures during CI build + tests:

### 1. Compile syntax error in \`page!\` / \`watch!\` macro emission

\`\`\`
error: expected \`:\`
  --> ... line 24,  state: { loading, error },
  --> ... line 120, state: { loading, error },
  --> ... line 184, state: { loading, error },
\`\`\`

Three call sites in the tutorial code generate emissions ending with \`state: { loading, error },\` that fail Rust parsing. Likely the \`page!\` or \`watch!\` macro contract has changed and the tutorial's hand-written usage is out of date.

### 2. \`ResolvedUrls::resolve_client_url\` not found

\`\`\`
error[E0599]: no method named \`resolve_client_url\` found for struct \`ResolvedUrls\` in the current scope
\`\`\`

\`ResolvedUrls\` no longer exposes \`resolve_client_url\` as an inherent method. The tutorial references the old API directly. The new API likely requires bringing \`ClientUrlResolver\` into scope or using the typed accessor introduced in PR #4518 \`fix(macros): typed ResolvedUrls accessors for ViewSet and #[action]\` and PR #4580 \`docs(examples): migrate examples-tutorial-rest to typed ResolvedUrls accessor\` (which migrated \`examples-tutorial-rest\` — the equivalent migration was missed for \`examples-tutorial-basis\`).

### 3. Superuser inventory test panic

\`\`\`
FAIL [   0.013s] (11/28) examples-tutorial-basis::createsuperuser tutorial_user_is_registered_in_superuser_creator_inventory
thread 'tutorial_user_is_registered_in_superuser_creator_inventory' panicked at examples-tutorial-basis/tests/createsuperuser.rs:106:5
\`\`\`

The tutorial \`User\` type is not appearing in the \`SuperuserCreator\` inventory expected by the test. This likely interacts with the framework changes from PR #4545 \`feat(core): auto-register SuperuserCreator for any #[user] + #[model] type\` and PR #4544 \`fix(examples-tutorial-basis): wire createsuperuser for minimal user model\`.

## Reproduction

\`\`\`
cd examples/examples-tutorial-basis
cargo build --all-features
cargo nextest run --all-features
\`\`\`

Observed CI failure on PR #4595 \`chore: release\`: <https://github.com/kent8192/reinhardt-web/actions/runs/26040399559/job/76619077831>

## Expected behavior

\`examples-tutorial-basis\` compiles and all tests pass under the current framework version.

## Suggested fix

Three sub-fixes within the same examples crate (single PR per WU-2):

1. Migrate \`page!\` / \`watch!\` call sites (lines around 24, 120, 184) to the current macro contract — likely change \`state: { loading, error }\` to the new syntax.
2. Replace \`resolved_urls.resolve_client_url(...)\` calls with the typed accessor pattern from PR #4518 / #4580 (e.g., \`use reinhardt::ClientUrlResolver;\` then call via trait, or use \`urls.client().<app>().<route>(...)\`).
3. Diagnose why the tutorial \`User\` is not auto-registered in \`SuperuserCreator\` inventory after PR #4545 — verify \`#[user] + #[model]\` placement, feature flags, and the test's expectation against the new inventory contract.

## Environment

- Crate: \`examples-tutorial-basis\`
- Related: PR #4518, #4544, #4545, #4580
