### ISSUE TITLE
bug(macros): #[url_patterns(mode = ws)] generates call to non-existent WebSocketRouter::with_namespace

### ISSUE THREAD

**Issue by kent8192** [kent8192/reinhardt-web#3829]
## Bug Description

The `#[url_patterns(mode = ws)]` attribute macro (introduced in #3782) emits a wrapper that calls `__router.with_namespace(...)` on the function's return value. When the function returns a `WebSocketRouter`, this fails to compile because `WebSocketRouter` does not implement `with_namespace`. The shared `build_wrapper_and_assertion` helper (`crates/reinhardt-core/macros/src/url_patterns.rs`) emits the same wrapper for all four modes (server, client, unified, ws), but `with_namespace` is only available on `ServerRouter`, `ClientRouter`, and `UnifiedRouter`.

## Steps to Reproduce

```rust
use reinhardt::WebSocketRouter;
use reinhardt::url_patterns;
use crate::config::apps::InstalledApp;

#[url_patterns(InstalledApp::auth, mode = ws)]
pub fn ws_url_patterns() -> WebSocketRouter {
    WebSocketRouter::new()
}
```

Compile any crate consuming this:

```
error[E0599]: no method named `with_namespace` found for struct `WebSocketRouter` in the current scope
```

Reproduced against `kent8192/reinhardt-web@eb6107d5` (branch `main`).

## Expected Behavior

`#[url_patterns(mode = ws)]` should compile against an empty `WebSocketRouter::new()` (no consumers), generating only the `ws_url_resolvers` module without producing an invalid `with_namespace` call. Either:

- Add `WebSocketRouter::with_namespace(self, &str) -> Self` (parallel to `ServerRouter`), or
- Adjust `build_wrapper_and_assertion` to skip namespace-wrapping for `mode = ws` (since WebSocket route paths are absolute today and not namespaced via prefix).

## Actual Behavior

```
error[E0599]: no method named `with_namespace` found for struct `WebSocketRouter` in the current scope
   --> dashboard/src/apps/auth/ws_urls.rs:14:1
    |
14  | #[url_patterns(InstalledApp::auth, mode = ws)]
    | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ method not found in `WebSocketRouter`
```

## Environment

- Rust version: 1.94.0
- OS: macOS 25.3 / Linux x86_64 (Ubuntu 24.04 CI)
- reinhardt-web revision: `eb6107d5e19e2e06d83784fce42fde86a5259f94` (branch `main`)

## Additional Context

- Surfaced while migrating `kent8192/reinhardt-cloud` dashboard to the new typed `#[url_patterns]` API (cloud-side tracking issue forthcoming).
- All three apps that have no per-handler WebSocket consumers cannot satisfy `#[routes]`'s expectation of a `<app>::ws_urls::ws_url_resolvers::__for_each_ws_url_resolver!` symbol, because `mode = ws` itself does not compile on `WebSocketRouter`.
- Related upstream PRs: #3782 (introduced `mode = ws`), #3812 (fixed 5 other ws macro bugs).
