### ISSUE TITLE
Bug: #[settings] macro generates unresolvable bare identifiers for CoreSettings/HasCoreSettings

### ISSUE THREAD

**Issue by kent8192** [kent8192/reinhardt-web#2855]
## Prerequisites

- [x] I have searched existing issues to verify this bug hasn't been reported

## Bug Description

The `#[settings()]` proc macro generates code that references `CoreSettings` and `HasCoreSettings` as bare identifiers (not fully qualified paths). When the macro is used via `use reinhardt::settings;`, these types are not in scope, causing compilation errors.

This regression was introduced by PR #2848, which re-exported the `settings` attribute macro at the `reinhardt` crate root. The re-export itself is correct, but the macro's generated code assumes `CoreSettings` and `HasCoreSettings` are already imported by the user.

## Steps to Reproduce

1. Use the `#[settings()]` macro in an example or user project:
```rust
use reinhardt::settings;

#[settings()]
struct ProjectSettings;
```
2. Compile the project
3. Observe compilation errors

## Expected Behavior

The `#[settings()]` macro should compile successfully without requiring the user to manually import `CoreSettings` and `HasCoreSettings`.

## Actual Behavior

Compilation fails with:
```
error[E0412]: cannot find type `CoreSettings` in this scope
error[E0405]: cannot find trait `HasCoreSettings` in this scope
```

This breaks all examples that use `#[settings()]`: `examples-hello-world`, `examples-rest-api`, `examples-database-integration`, `examples-tutorial-basis`, `examples-tutorial-rest`, `examples-github-issues`, `examples-twitter`.

## Environment

- Rust version: 1.91.1
- OS: Ubuntu 24.04 (CI), macOS (local)
- Crate version: reinhardt-macros 0.1.0-rc.14

## Additional Context

- **Root cause**: `crates/reinhardt-core/macros/src/settings_compose.rs` generates `format_ident!("{}", type_name)` for fragment types and `format_ident!("Has{}", type_name)` for trait names, producing bare identifiers instead of fully qualified paths.
- **Fix**: Use `#conf_crate::CoreSettings` and `#conf_crate::HasCoreSettings` (fully qualified via `reinhardt_conf`) in the generated code.
- **Affected CI**: All example tests fail on the release-plz PR #2853.
- **Introduced by**: PR #2848 (fix: initialize ORM global state and re-export settings macro)
