### ISSUE TITLE
Bug: `#[server_fn]` generates type mismatch for WASM target after URL prefix resolution (#3148)

### ISSUE THREAD

**Issue by kent8192** [kent8192/reinhardt-web#3154]
## Prerequisites

- [x] I have searched existing issues to verify this bug hasn't been reported

## Bug Description

The `#[server_fn]` macro generates code that passes a `String` where `gloo-net`'s `Request::post()` expects `&str` when compiling for `wasm32-unknown-unknown` target. This was introduced by PR #3148 which changed the server_fn URL resolution to use a prefix-based approach. The generated code constructs a `String` for the URL but does not convert it to `&str` before passing it to `gloo-net`'s API.

## Steps to Reproduce

1. Create a component using `#[server_fn]` macro (e.g., in `reinhardt-admin`)
2. Build for `wasm32-unknown-unknown` target: `cargo build --target wasm32-unknown-unknown`
3. Observe compilation error

## Expected Behavior

The `#[server_fn]` macro should generate code that correctly converts the resolved URL `String` to `&str` before passing it to `gloo-net`'s `Request::post()`.

## Actual Behavior

Compilation fails with:

```
error[E0308]: mismatched types -- expected `&str`, found `String`
```

Affected files include:
- `crates/reinhardt-admin/src/server/update.rs:52`
- And likely other `server_fn`-annotated functions across the codebase

## Environment

- Rust version: stable (2024 edition)
- Target: `wasm32-unknown-unknown`
- OS: macOS
- Introduced by: PR #3148 (URL prefix resolution change)

## Additional Context

The fix should ensure the macro-generated code calls `.as_str()` or uses `&` to convert the `String` to `&str` before passing it to `gloo-net`'s `Request::post()`. This affects all `#[server_fn]`-annotated functions when compiled for WASM targets.
