### PR TITLE
fix(model-macros): include ForeignKeyField<T> in typestate builder

### LINKED ISSUE #4413: bug(model-macros): typestate Model::build() drops ForeignKeyField<T> fields
## Bug Description

The `#[model]` derive's new typestate `Model::build()` constructor (introduced in rc.30 via PR #4406) does not emit setters for `ForeignKeyField<T>` fields. Models with foreign-key relationship fields fail to compile when consumers reference them on the generated `*Builder` type.

## Steps to Reproduce

1. Define a model with `pub user: ForeignKeyField<User>` (see `examples/examples-twitter/src/apps/tweet/models/tweet.rs`).
2. Build the workspace: `cargo make build` or `cargo check -p examples-twitter`.

## Observed

```
error[E0609]: no field `user_id` on type `TweetBuilder<TweetBuilderSet, ...>`
  --> examples-twitter/src/apps/tweet/models/tweet.rs:28:6
   |
28 |     pub user: ForeignKeyField<User>,
   |         ^^^^ unknown field
   |
   = note: available fields are: `content`, `like_count`, `retweet_count`, `__state`
```

The `user` (and any `ForeignKeyField<T>`) field is completely missing from the generated `Builder` struct/setters. Same error appears in `examples-twitter` (`password_reset_token.rs`, `dm/models/message.rs`, `tweet.rs`) and `examples/examples-tutorial-basis`.

## Expected

The `Builder` should expose a setter accepting `impl IntoPrimaryKey<Related>` (or equivalent) for every `ForeignKeyField<T>` declared on the model, mirroring how `Model::new(...)` already handles them.

## Suspected Root Cause

`crates/reinhardt-core/macros/src/model_derive.rs` around `generate_build_function` (~lines 4009–4100) classifies fields into `SetterKind` variants. The `fk_id_to_fk_field` map only contains synthetic `*_id` aliases, so the real `ForeignKeyField<T>` field is filtered out of the setter-emission loop.

## Environment

- Rust: 1.94.1 (workspace MSRV)
- Branch: `main` (commit `f0a3cda3e` and later)
- First broken on: PR #4406 merge (`fdd83870c`)

## Impact

Blocks PR #4409 (release-plz `chore: release` rc.30) CI on `Examples Tests / examples-twitter` and `Examples Tests / examples-tutorial-basis`.

### PR DESCRIPTION
**Pull request by kent8192**
## Summary

Fix the typestate `Model::build()` constructor (introduced in #4406) so it no longer drops `ForeignKeyField<T>` fields. The generated `*Builder` struct now exposes a setter for every FK relation that mirrors `Model::new()`'s signature (`impl IntoPrimaryKey<Related>`), restoring compilation for any model with a foreign key.

## Type of Change

- [x] Bug fix (non-breaking change that fixes an issue)

## Motivation and Context

The typestate builder added in PR #4406 silently omitted FK `*_id` fields. Any model with a `ForeignKeyField<T>` (e.g. `Tweet`, `DMMessage`, `PasswordResetToken`, the tutorial-basis `Question`) failed to compile when calling `.user(...)`, `.room(...)`, etc., on the builder:

```
error[E0609]: no field `user_id` on type `TweetBuilder<...>`
   = note: available fields are: `content`, `like_count`, `retweet_count`, `__state`
```

Root cause: `is_auto_generated_field` returns `true` for FK `*_id` fields, so they are filtered out of `user_fields` in `generate_build_function`. `generate_new_function` already handled this with a dedicated loop over `fk_id_field_names`; `build()` did not — the `fk_id_to_fk_field.get(&name_str)` branch inside `build()`'s `user_fields` loop was dead code.

The fix mirrors `new()`'s approach: after walking `user_fields`, iterate `fk_id_field_names` and push one `SetterKind::ForeignKey` `Required` entry per FK `*_id` field. The setter is named after the related FK field (e.g. `user`) and accepts `impl IntoPrimaryKey<T>`, so callers can pass either `&user` or a raw primary-key value. The existing `fk_id_assignments` block in `finish()` already unwraps `self.user_id`, so no other change was needed.

Fixes #4413

## How Was This Tested?

- `cargo check -p examples-twitter --all-features` — passes (previously failed with 4× E0609 across `tweet.rs`, `message.rs`, `password_reset_token.rs`)
- `cargo check -p examples-tutorial-basis --all-features` — passes
- `cargo nextest run -p reinhardt-macros --all-features` — 198/198 pass (including the trybuild UI suite)
- `cargo make fmt-check` — clean

## Breaking Changes

None. The new setters are additive to the generated builder; existing call sites that use `Model::new(...)` or builders without FK setters are unaffected.

## Labels to Apply

- `bug`
- `high`

🤖 Generated with [Claude Code](https://claude.com/claude-code)

### CODE REVIEW

File: crates/reinhardt-core/macros/src/model_derive.rs [hunk 1]
```diff
@@ -4099,6 +4100,39 @@ fn generate_build_function(
...
+		let Some(id_field_info) = field_infos.iter().find(|fi| fi.name == *fk_id_name) else {
+			continue;
+		};
+		let fk_field_info = field_infos.iter().find(|fi| fi.name == *fk_field_name);
+		let related_type = match fk_field_info {
+			Some(info) => extract_foreign_key_target_type(&info.ty),
+			// Defensive fallback: use the `*_id` storage type itself.
+			None => id_field_info.ty.clone(),
+		};
+		let setter_name = syn::Ident::new(fk_field_name, fk_id_name.span());
```
[the remark this answers is not in the document]
Comment (kent8192) [reply crates/reinhardt-core/macros/src/model_derive.rs]: Addressed in 3cf8db33. The setter Ident now reuses `fk_field_info.name.clone()` when the related FK field is present (preserves raw-ident spelling and span), and falls back to `syn::Ident::new_raw` so the macro never panics on Rust keywords like `type`.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

File: crates/reinhardt-core/macros/src/model_derive.rs [hunk 2]
```diff
@@ -4099,6 +4100,39 @@ fn generate_build_function(
...
+		let fk_id_str = fk_id_name.to_string();
+		// Look up the related FK field name (e.g. `user_id` -> `user`).
+		let Some(fk_field_name) = fk_id_to_fk_field.get(&fk_id_str) else {
+			continue;
+		};
+		// Look up the FieldInfo for both the `*_id` field (for its storage type)
+		// and the related FK field (for the related model type).
+		let Some(id_field_info) = field_infos.iter().find(|fi| fi.name == *fk_id_name) else {
+			continue;
+		};
```
[the remark this answers is not in the document]
Comment (kent8192) [reply crates/reinhardt-core/macros/src/model_derive.rs]: Partially addressed in 3cf8db33. The `id_field_info` lookup now panics with an explanatory message when `fk_id_field_names` desyncs from `field_infos` (a true internal invariant violation). The earlier `fk_id_to_fk_field.get(&fk_id_str)` `continue` is intentional, since `fk_id_to_fk_field` is constructed to retain only `*_id`-suffixed names — names that don't follow the convention are deliberately skipped, mirroring `generate_new_function`. A comment was added to make this explicit.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

File: crates/reinhardt-core/macros/src/model_derive.rs [hunk 3]
```diff
@@ -4099,6 +4100,39 @@ fn generate_build_function(
...
+		let fk_field_info = field_infos.iter().find(|fi| fi.name == *fk_field_name);
```
[the remark this answers is not in the document]
Comment (kent8192) [reply crates/reinhardt-core/macros/src/model_derive.rs]: Not addressed in this PR. The linear scan runs once per FK field at proc-macro expansion time, and models in this codebase rarely have more than a handful of FKs (typical: 1–5; large model like `DMMessage` has ~3). The overhead is negligible compared to the surrounding macro work, and pre-indexing would add complexity for no measurable gain. Happy to revisit if a model with many FKs becomes a real bottleneck.

🤖 Generated with [Claude Code](https://claude.com/claude-code)

File: crates/reinhardt-core/macros/src/model_derive.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (kent8192) [reply crates/reinhardt-core/macros/src/model_derive.rs]: Follow-up in 19119400. Two additional cases hardened: (1) defensive `r#` prefix strip before `Ident::new_raw` per the Copilot suggestion, since `new_raw` expects the bare name; (2) reserved identifiers that even `Ident::new_raw` rejects (`self`/`Self`/`super`/`crate`/`extern`) are now surfaced as a `syn::Error` compile message instead of letting the underlying `proc_macro2` panic escape.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
