### ISSUE TITLE
Bug: #[export_endpoints] requires nightly Rust features (inner proc macro attributes)

### ISSUE THREAD

**Issue by kent8192** [kent8192/reinhardt-web#3709]
## Description

The `#[export_endpoints]` attribute macro is documented as an inner attribute (`#![reinhardt::export_endpoints]`), but inner macro attributes require the unstable feature `custom_inner_attributes` (rust-lang/rust#54726). Additionally, `pub mod name;` declarations inside proc macro input trigger `file modules in proc macro input are unstable` (rust-lang/rust#54727).

Both features are nightly-only, making `#[export_endpoints]` unusable on stable Rust.

## Steps to Reproduce

1. Create a `views.rs` file with the inner attribute:

```rust
#![reinhardt::export_endpoints]

pub mod login;
pub mod register;
```

2. Build on stable Rust 1.94.1

## Expected Behavior

`#[export_endpoints]` should work on stable Rust, consistent with the project's `rust-toolchain.toml` (`channel = "1.94.1"`).

## Actual Behavior

```
error[E0658]: inner macro attributes are unstable
  --> dashboard/src/apps/auth/views.rs:2:4
   |
2  | #![reinhardt::export_endpoints]
   |    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   = note: see issue #54726 <https://github.com/rust-lang/rust/issues/54726>

error[E0658]: file modules in proc macro input are unstable
  --> dashboard/src/apps/auth/views.rs:4:1
   |
4  | pub mod login;
   | ^^^^^^^^^^^^^^
   = note: see issue #54727 <https://github.com/rust-lang/rust/issues/54727>
```

## Impact

Without `#[export_endpoints]`, consuming crates cannot re-export `__url_resolver_*` modules from per-file view modules. This blocks adoption of `#[url_patterns]` and removal of `#[routes(standalone)]` workaround.

## Suggested Fix

Consider an outer attribute form that works on stable Rust:

```rust
// Option A: outer attribute on module with inline body
#[reinhardt::export_endpoints]
mod views {
    pub mod login;
    pub mod register;
}

// Option B: declarative macro alternative
reinhardt::export_endpoints! {
    pub mod login;
    pub mod register;
}
```

## Environment

- Rust: 1.94.1 (stable)
- reinhardt-web: main branch (63ba983a)
- OS: macOS

🤖 Generated with [Claude Code](https://claude.com/claude-code)

**Comment by kent8192** [comment]
Tracking in kent8192/reinhardt-cloud#352.

🤖 Generated with [Claude Code](https://claude.com/claude-code)
